# Generated by Django 5.0.6 on 2024-06-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0002_alter_servicios_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(null='media/default.png', upload_to='servicios/'),
        ),
    ]
